### ISSUE TITLE
Entanglement Generation Emit Time Throws Error for Non-negligible Positive Coherence Times

### ISSUE THREAD

**Issue by DMcDe** [sequence-toolbox/SeQUeNCe#194]
When using Memory with coherence times greater than roughly 1e-12, the entanglement generation message reception throws an error because the message emit time is not the same as the emit time calculated by the schedule_transmit method.

```
Cell In[4], line 77, in Game.start(self, games)
     75         self.a.protocols[0].start()
     76         self.b.protocols[0].start()
---> 77         self.tl.run()
     78 else:
     79     if (self.a.get_components_by_type('MemoryWithRandomCoherenceTime')[0].entangled_memory['node_id'] != None):

File ~\anaconda3\envs\sequence\Lib\site-packages\sequence\kernel\timeline.py:133, in Timeline.run(self)
    130         continue
    132     self.time = event.time
--> 133     event.process.run()
    134     self.run_counter += 1
    136 self.is_running = False

File ~\anaconda3\envs\sequence\Lib\site-packages\sequence\kernel\process.py:31, in Process.run(self)
     25 def run(self) -> None:
     26     """Method to execute process.
     27 
     28     Will run the `activation_method` method of `owner` with `act_params` passed as args.
     29     """
---> 31     return getattr(self.owner, self.activation)(*self.act_params, **self.act_kwargs)

File ~\anaconda3\envs\sequence\Lib\site-packages\sequence\topology\node.py:148, in Node.receive_message(self, src, msg)
    146 if msg.receiver is not None:
    147     for protocol in self.protocols:
--> 148         if protocol.name == msg.receiver and protocol.received_message(src, msg):
    149             return
    150 else:

File ~\anaconda3\envs\sequence\Lib\site-packages\sequence\entanglement_management\generation.py:346, in EntanglementGenerationA.received_message(self, src, msg)
    344 # schedule emit
    345 emit_time = self.own.schedule_qubit(self.middle, msg.emit_time)
--> 346 assert emit_time == msg.emit_time, \
    347     "Invalid eg emit times %d %d %d" % (emit_time,  msg.emit_time, self.own.timeline.now())
    349 process = Process(self, "emit_event", [])
    350 event = Event(msg.emit_time, process)

AssertionError: Invalid eg emit times 1166454635412500 1166454635400000 1166454635388996
```

Program works normally when coherence time is set to 0 (or any negative number, strangely). When coherence time is very small, program runs without error but does not terminate.

**Comment by caitaozhan** [comment]
I will take a look into it.

**Comment by caitaozhan** [comment]
Hi DMcDe,

I could not replicate your issue. Please paste the code that leads to this issue.

Some information for you:

- The coherence_time leads to an expire event in the quantum memory. Check `Memory.update_state()` and `Memory.expire()` function. 
- You can use the following logging method to assist you in finding the reason for the bug:
```
import sequence.utils.log as log

log_filename = 'log_filename'
log.set_logger(__name__, tl, log_filename)
log.set_logger_level('DEBUG')
modules = ['timeline', 'generation']    # put more module names here
for module in modules:
    log.track_module(module)
```

**Comment by DMcDe** [comment]
Hi,

The code that leads to the issue is part of a longer module, which is [this file](https://github.com/DMcDe/CHSH-game-introduction/blob/main/chsh-simulation-sequence.ipynb) in a repo on my profile. The file currently uploaded has coherence time of 0, but changing it to a larger number as described above causes the error pasted.

I have tried digging into the update_state and expire methods but couldn't find the error there. I will try using the logging as well.

I appreciate your help!

**Comment by caitaozhan** [comment]
Hi DMcDe,

I understand your code and your problem now.

`When coherence time is very small, program runs without error but does not terminate.`
Answer: this is because the entanglement is never successfully, since the coherence time is too small. You need some certain amount of coherence time to keep the qubits alive. When coherence time is too small, you will never enter the first game's `self.play_round()`


That `AssertionError: Invalid eg emit times 1166454635412500 1166454635400000 1166454635388996` is fixed by the new `Manager.update()` function in [correct CHSH](https://github.com/caitaozhan/testing/blob/master/quantum/CHSH_game.py).  Also remember to update your SeQUeNCe to version 0.6.3, because some syntax have changed. When the entnaglement is sucessful, you have to remove the memory.expiration_event from the timeline. If the expire event is there, the entanglement will be gone before you enter the `self.play_round()`, i.e., the entanglement failed.

How you change then coherence time in [correct CHSH](https://github.com/caitaozhan/testing/blob/master/quantum/CHSH_game.py) in the range of `[1e-12, 1e-11, 1e-10, ..., 1e-2, 1e-1, 1]`, you will observe the correct behavior.

Thanks,
Caitao

**Comment by caitaozhan** [comment]
This Issue will be closed unless @DMcDe raises another question.
